{"version": "3.0", "report": {"type": "CleanSuite", "id": "Kleenex", "fullid": "Kleenex", "idlist": ["Kleenex"], "name": "Kleenex", "starttime": "2021-02-11 06:36:47.803603", "stoptime": "2021-02-11 06:37:18.880662", "runtime": 31.077059, "cli": "/home/osboxes/pyATS/bin/pyats clean --testbed-file ../tbed.yml --clean-file clean.yml --clean-device R1", "host": "osboxes", "submitter": "root", "summary": {"passed": 0, "passx": 0, "failed": 0, "errored": 0, "aborted": 0, "blocked": 0, "skipped": 0, "total": 0, "success_rate": 0.0}, "pluginsummary": {"passed": 0, "passx": 0, "failed": 1, "errored": 0, "aborted": 0, "blocked": 0, "skipped": 0, "total": 1, "success_rate": 0.0}, "extra": {"testbed": "tbed"}, "totaltasks": 0, "tasks": [{"type": "Standalone", "id": "Standalone-1", "fullid": "Standalone-1", "idlist": ["Standalone-1"], "name": "Kleenex", "starttime": "2021-02-11 06:36:47.805386", "stoptime": "2021-02-11 06:37:18.880280", "runtime": 31.074894, "logfile": "Kleenex.log", "summary": {"passed": 0, "passx": 0, "failed": 1, "errored": 0, "aborted": 0, "blocked": 0, "skipped": 0, "total": 1, "success_rate": 0.0}, "result": {"value": "failed"}, "extra": {"clean_files": ["clean.yml"]}, "sections": [{"type": "Device", "id": "R1", "fullid": "Standalone-1.R1", "idlist": ["Standalone-1", "R1"], "name": "R1", "starttime": "2021-02-11 06:36:47.850319", "stoptime": "2021-02-11 06:37:18.478102", "runtime": 30.627783, "logs": {"file": "Kleenex.R1.log", "begin": 142, "begin_lines": 1, "size": 16717, "size_lines": 203}, "result": {"value": "failed", "reason": "Caught error while attempting to clean device:\n  cleaner = PyatsDeviceClean\n   device = Device R1, type ios\n      pid = 14473\n\n", "data": "Traceback (most recent call last):\n  File \"src/pyats/kleenex/worker.py\", line 101, in pyats.kleenex.worker.KleenexWorker.run\n  File \"/home/osboxes/pyATS/lib/python3.8/site-packages/genie/libs/clean/clean.py\", line 264, in clean\n    super().clean(device, reporter, *args, **kwargs)\n  File \"/home/osboxes/pyATS/lib/python3.8/site-packages/genie/libs/clean/clean.py\", line 258, in clean\n    raise Exception(\"Clean {result}.\".format(result=str(result)))\nException: Clean failed.\n"}, "details": ["Caught error while attempting to clean device:\n  cleaner = PyatsDeviceClean\n   device = Device R1, type ios\n      pid = 14473\n\nTraceback (most recent call last):\n  File \"src/pyats/kleenex/worker.py\", line 101, in pyats.kleenex.worker.KleenexWorker.run\n  File \"/home/osboxes/pyATS/lib/python3.8/site-packages/genie/libs/clean/clean.py\", line 264, in clean\n    super().clean(device, reporter, *args, **kwargs)\n  File \"/home/osboxes/pyATS/lib/python3.8/site-packages/genie/libs/clean/clean.py\", line 258, in clean\n    raise Exception(\"Clean {result}.\".format(result=str(result)))\nException: Clean failed.\n"], "extra": {"cleaner": "PyatsDeviceClean", "device_clean": {"connect": {"timeout": 100}, "reload": {"reload_service_args": {"timeout": 600, "reload_creds": "default", "prompt_recovery": true}}, "apply_configuration": {"configuration": "hostname PE1"}, "order": ["connect", "apply_configuration", "reload"], "images": []}}, "sections": [{"type": "Testcase", "id": "CleanTestcase", "fullid": "Standalone-1.R1.CleanTestcase", "idlist": ["Standalone-1", "R1", "CleanTestcase"], "name": "CleanTestcase", "starttime": "2021-02-11 06:36:47.936676", "stoptime": "2021-02-11 06:37:18.475304", "runtime": 30.538628, "xref": {"file": "/home/osboxes/pyATS/lib/python3.8/site-packages/genie/libs/clean/clean.py", "line": 44}, "logs": {"file": "Kleenex.R1.log", "begin": 142, "begin_lines": 1, "size": 16572, "size_lines": 202}, "result": {"value": "failed"}, "sections": [{"type": "TestSection", "id": "connect", "fullid": "Standalone-1.R1.CleanTestcase.connect", "idlist": ["Standalone-1", "R1", "CleanTestcase", "connect"], "name": "connect", "starttime": "2021-02-11 06:36:48.065611", "stoptime": "2021-02-11 06:36:49.679972", "runtime": 1.614361, "description": " This stage connects to the device that is being cleaned.\n\n    Stage Schema\n    ------------\n    connect:\n        timeout (int, optional): Connection timeout. Defaults to 200.\n        retry_timeout (int, optional): Overall timeout for retry mechanism. Defaults to 0 which means no retry.\n        retry_interval (int, optional): Interval for retry mechanism. Defaults to 0 which means no retry.\n\n    Example\n    -------\n    connect:\n        timeout: 60\n\n    ", "xref": {"file": "unknown", "line": 0}, "logs": {"file": "Kleenex.R1.log", "begin": 142, "begin_lines": 1, "size": 6380, "size_lines": 125}, "parameters": {"device": "<Device R1 at 0x7fd466048760>", "timeout": 100}, "result": {"value": "passed", "reason": "Successfully connected to 'R1'"}}, {"type": "TestSection", "id": "apply_configuration", "fullid": "Standalone-1.R1.CleanTestcase.apply_configuration", "idlist": ["Standalone-1", "R1", "CleanTestcase", "apply_configuration"], "name": "apply_configuration", "starttime": "2021-02-11 06:36:49.681972", "stoptime": "2021-02-11 06:37:04.673290", "runtime": 14.991318, "description": " Apply configuration on the device, either by providing a file and/or\n    raw configuration.\n\n    Stage Schema\n    ------------\n    apply_configuration:\n        configuration: <Configuration block to be applied, 'str'> (Optional)\n        configuration_from_file: <File that contains a configuration to apply, 'str'> (Optional)\n        file: <Configuration file for config replace> (Optional)\n        configure_replace: <Use configure replace instead of copy 'bool'> (Optional)\n        config_timeout: <Timeout in seconds, 'int'> (Optional)\n        config_stable_time: <Time for configuration stability in seconds, 'int'> (Optional)\n        copy_vdc_all: <To copy on all VDCs or not, 'bool'> (Optional)\n        max_time: <Maximum time section will take for checks in seconds, 'int'> (Optional)\n        check_interval: <Time interval, 'int'> (Optional)\n        skip_copy_run_start: <Option to skip copy run start. Default False. 'bool'> (Optional)\n\n    Example\n    -------\n    apply_configuration:\n        configuration: |\n            interface ethernet2/1\n            no shutdown\n        file: bootflash:/ISSUCleanGolden.cfg\n        configure_replace: True\n        config_timeout: 600\n        config_stable_time: 10\n        copy_vdc_all: True\n        max_time: 300\n        check_interval: 20\n\n    ", "xref": {"file": "unknown", "line": 0}, "logs": {"file": "Kleenex.R1.log", "begin": 6522, "begin_lines": 126, "size": 6265, "size_lines": 49}, "parameters": {"device": "<Device R1 at 0x7fd466048760>", "configuration": "hostname PE1"}, "result": {"value": "passed", "reason": "Successfully applied configuration after reloading device R1"}, "sections": [{"type": "Step", "id": "STEP 1", "fullid": "Standalone-1.R1.CleanTestcase.apply_configuration.STEP 1", "idlist": ["Standalone-1", "R1", "CleanTestcase", "apply_configuration", "STEP 1"], "name": "Apply configuration to device R1 after reload", "starttime": "2021-02-11 06:36:50.011024", "stoptime": "2021-02-11 06:36:50.113035", "runtime": 0.102011, "xref": {"file": "/home/osboxes/pyATS/lib/python3.8/site-packages/genie/libs/clean/clean.py", "line": 249}, "logs": {"file": "Kleenex.R1.log", "begin": 7612, "begin_lines": 133, "size": 1228, "size_lines": 12}, "result": {"value": "passed", "reason": "Successfully applied configuration to device R1 "}, "extra": {"continue_": false}}, {"type": "Step", "id": "STEP 2", "fullid": "Standalone-1.R1.CleanTestcase.apply_configuration.STEP 2", "idlist": ["Standalone-1", "R1", "CleanTestcase", "apply_configuration", "STEP 2"], "name": "Copy running-config to startup-config on device R1", "starttime": "2021-02-11 06:36:50.114412", "stoptime": "2021-02-11 06:36:54.649547", "runtime": 4.535135, "xref": {"file": "/home/osboxes/pyATS/lib/python3.8/site-packages/genie/libs/clean/clean.py", "line": 249}, "logs": {"file": "Kleenex.R1.log", "begin": 8840, "begin_lines": 145, "size": 1553, "size_lines": 15}, "result": {"value": "passed", "reason": "Successfully copied running-config to startup-config on R1"}, "extra": {"continue_": false}}, {"type": "Step", "id": "STEP 3", "fullid": "Standalone-1.R1.CleanTestcase.apply_configuration.STEP 3", "idlist": ["Standalone-1", "R1", "CleanTestcase", "apply_configuration", "STEP 3"], "name": "Allow configuration to stabilize on device R1", "starttime": "2021-02-11 06:36:54.650618", "stoptime": "2021-02-11 06:37:04.667300", "runtime": 10.016682, "xref": {"file": "/home/osboxes/pyATS/lib/python3.8/site-packages/genie/libs/clean/clean.py", "line": 249}, "logs": {"file": "Kleenex.R1.log", "begin": 10393, "begin_lines": 160, "size": 986, "size_lines": 6}, "result": {"value": "passed", "reason": "Successfully applied configuration after reloading device R1"}, "extra": {"continue_": false}}]}, {"type": "TestSection", "id": "reload", "fullid": "Standalone-1.R1.CleanTestcase.reload", "idlist": ["Standalone-1", "R1", "CleanTestcase", "reload"], "name": "reload", "starttime": "2021-02-11 06:37:04.674679", "stoptime": "2021-02-11 06:37:05.451452", "runtime": 0.776773, "description": " This stage reloads the device.\n\n    Stage Schema\n    ------------\n    reload:\n        reload_service_args: (Optional, if not specified defaults below are used)\n            timeout: <reload timeout value, default 800 seconds. 'int'> (Optional)\n            reload_creds: <Credential name defined in the testbed yaml file to be used during reload, default 'default'. 'str'> (Optional)\n            prompt_recovery: <Enable/Disable prompt recovery feature, 'bool'> (Optional)\n            <Key>: <Value> (Any other key:value pairs that the unicon reload service allows for)\n\n        check_modules:\n            check: <Enable/Disable checking of modules after reload, default 'True'. 'bool'> (Optional)>\n            timeout: <timeout value to verify modules are in stable state, default 180 seconds. 'int'> (Optional)\n            interval: <interval value between checks for verifying module status, default 30 seconds. 'int'> (Optional)\n\n\n    Example\n    -------\n    reload:\n        reload_service_args:\n            timeout: 600\n            reload_creds: clean_reload_creds\n            prompt_recovery: True\n            reconnect_sleep: 200 (Unicon NXOS reload service argument)\n\n        check_modules:\n            check: False\n\n    ", "xref": {"file": "unknown", "line": 0}, "logs": {"file": "Kleenex.R1.log", "begin": 12787, "begin_lines": 175, "size": 3378, "size_lines": 25}, "parameters": {"device": "<Device R1 at 0x7fd466048760>", "reload_service_args": {"timeout": 600, "reload_creds": "default", "prompt_recovery": 1}}, "result": {"value": "failed"}, "sections": [{"type": "Step", "id": "STEP 1", "fullid": "Standalone-1.R1.CleanTestcase.reload.STEP 1", "idlist": ["Standalone-1", "R1", "CleanTestcase", "reload", "STEP 1"], "name": "Reload 'R1'", "starttime": "2021-02-11 06:37:04.691631", "stoptime": "2021-02-11 06:37:05.446475", "runtime": 0.754844, "xref": {"file": "/home/osboxes/pyATS/lib/python3.8/site-packages/genie/libs/clean/clean.py", "line": 249}, "logs": {"file": "Kleenex.R1.log", "begin": 13989, "begin_lines": 183, "size": 1259, "size_lines": 11}, "result": {"value": "failed", "reason": "'R1' failed to reload within 600 seconds.\nError: Reload failed ('Unable to read. Connection closed or not available', OSError(5, 'Input/output error'))"}, "extra": {"continue_": false}}]}]}]}]}]}}